### ISSUE TITLE
Checksum in manual

### ISSUE THREAD

**Issue by BasVanBoven** [therealmuffin/dynaudio-connect-api#2]
Hey! Thanks for the extensive documentation, this has been put to good use for some home automations :)

One mistake in the doc:

`ROUNDUP(SUM(payload)/255)*255-SUM(payload)-([Payload N]-ROUNDUP(SUM(payload/255)))
`

should probably be

`ROUNDUP(SUM(payload)/255)*255-SUM(payload)-([Payload N]-ROUNDUP(SUM(payload)/255))`

Also, it might be worth noting that the checksum calculation in the ods file will return the wrong result if opened with Microsoft Office. This is a problem of Microsoft, of course, but knowing this can save quite some headaches. :)

**Comment by therealmuffin** [comment]
Hello Bas,

Thanks for sharing your findings!

I've udated the documentation and renamed the ods file so it is clear in which application the generator can be properly opened.

Regards, Maarten
